services:
  - type: web
    name: todo-app
    env: java
    envVars:
      - key: PORT
        value: 8089
    buildCommand: "./mvnw clean install -DskipTests"
    startCommand: "java -jar target/*.jar"
    plan: free
