services:
  - type: web
    name: todo-app
    env: java
    envVars:
      - key: PORT
        value: 8089
      - key: DB_URL
        value: jdbc:mysql://localhost:3306/todo
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: 
    buildCommand: "./mvnw clean install -DskipTests"
    startCommand: "java -jar target/*.jar"
    plan: free
